// Copyright (c) 2026 BitConcepts, LLC
// SPDX-License-Identifier: LicenseRef-CPAC-Research-Evaluation-1.0
//! Golden vector generator - run manually to create test fixtures.
//!
//! Usage: cargo test -p cpac-engine --test generate_golden_vectors -- --ignored --nocapture

use cpac_engine::{compress, Backend, CompressConfig};
use std::fs;
use std::path::Path;

const GOLDEN_DIR: &str = "tests/fixtures/golden";

/// Helper to write a golden vector file.
fn write_golden(name: &str, data: &[u8]) {
    let path = Path::new(GOLDEN_DIR).join(name);
    fs::write(&path, data).unwrap();
    println!("✓ Generated: {}", path.display());
}

/// Generate golden vectors for all backends.
#[test]
#[ignore] // Run with --ignored
fn generate_backend_golden_vectors() {
    fs::create_dir_all(GOLDEN_DIR).unwrap();
    
    let test_data = b"The quick brown fox jumps over the lazy dog. ".repeat(100);
    
    // Test each backend
    for backend in [Backend::Zstd, Backend::Brotli, Backend::Raw] {
        let config = CompressConfig {
            backend: Some(backend),
            ..Default::default()
        };
        let result = compress(&test_data, &config).unwrap();
        let filename = format!("backend_{:?}.cpac", backend).to_lowercase();
        write_golden(&filename, &result.data);
    }
}

/// Generate golden vectors for edge cases.
#[test]
#[ignore]
fn generate_edge_case_golden_vectors() {
    fs::create_dir_all(GOLDEN_DIR).unwrap();
    
    // Empty file
    let config = CompressConfig::default();
    let result = compress(b"", &config).unwrap();
    write_golden("edge_empty.cpac", &result.data);
    
    // Single byte
    let result = compress(b"X", &config).unwrap();
    write_golden("edge_single_byte.cpac", &result.data);
    
    // Small file (< 256 bytes)
    let small_data = b"Small test data for golden vector validation.";
    let result = compress(small_data, &config).unwrap();
    write_golden("edge_small.cpac", &result.data);
    
    // Medium file (~4KB)
    let medium_data = vec![0xABu8; 4096];
    let result = compress(&medium_data, &config).unwrap();
    write_golden("edge_medium.cpac", &result.data);
    
    // Large repetitive file (triggers good compression)
    let large_data = b"ABCDEFGH".repeat(10000);
    let result = compress(&large_data, &config).unwrap();
    write_golden("edge_large_repetitive.cpac", &result.data);
}

/// Generate golden vectors for different data patterns.
#[test]
#[ignore]
fn generate_pattern_golden_vectors() {
    fs::create_dir_all(GOLDEN_DIR).unwrap();
    let config = CompressConfig::default();
    
    // Highly compressible text
    let text = b"The quick brown fox jumps over the lazy dog.\n".repeat(500);
    let result = compress(&text, &config).unwrap();
    write_golden("pattern_text_repetitive.cpac", &result.data);
    
    // CSV-like data
    let mut csv = String::from("id,name,value,status\n");
    for i in 0..1000 {
        csv.push_str(&format!("{i},item_{i},{},{}\n", 
            i * 7 % 1000,
            if i % 2 == 0 { "ok" } else { "err" }
        ));
    }
    let result = compress(csv.as_bytes(), &config).unwrap();
    write_golden("pattern_csv.cpac", &result.data);
    
    // JSON-like data
    let mut json = String::from("[");
    for i in 0..500 {
        json.push_str(&format!(
            r#"{{"id":{i},"name":"item_{i}","value":{}}}{}"#,
            i * 7 % 1000,
            if i < 499 { "," } else { "" }
        ));
    }
    json.push(']');
    let result = compress(json.as_bytes(), &config).unwrap();
    write_golden("pattern_json.cpac", &result.data);
    
    // Binary structured data
    let mut binary = Vec::new();
    for _ in 0..1000 {
        binary.extend_from_slice(&[0x01, 0x02, 0x03, 0x04]);
        binary.extend_from_slice(&[0xFF, 0xFE, 0xFD, 0xFC]);
    }
    let result = compress(&binary, &config).unwrap();
    write_golden("pattern_binary_structured.cpac", &result.data);
    
    // Random-like data (LCG)
    let mut rng: u64 = 42;
    let random: Vec<u8> = (0..8192)
        .map(|_| {
            rng = rng.wrapping_mul(6364136223846793005).wrapping_add(1);
            (rng >> 33) as u8
        })
        .collect();
    let result = compress(&random, &config).unwrap();
    write_golden("pattern_random.cpac", &result.data);
}

/// Generate metadata file documenting all golden vectors.
#[test]
#[ignore]
fn generate_golden_metadata() {
    let metadata = r#"# Golden Vector Test Fixtures

This directory contains golden vectors for regression testing.
Generated by: tests/generate_golden_vectors.rs

## Backend Variants
- backend_zstd.cpac     - Compressed with Zstd backend
- backend_brotli.cpac   - Compressed with Brotli backend
- backend_raw.cpac      - Compressed with Raw (no compression) backend

## Edge Cases
- edge_empty.cpac              - Empty file (0 bytes)
- edge_single_byte.cpac        - Single byte file
- edge_small.cpac              - Small file (< 256 bytes)
- edge_medium.cpac             - Medium file (~4KB)
- edge_large_repetitive.cpac   - Large repetitive data (high compression ratio)

## Data Patterns
- pattern_text_repetitive.cpac   - Repetitive English text
- pattern_csv.cpac               - CSV-formatted data (1000 rows)
- pattern_json.cpac              - JSON array (500 objects)
- pattern_binary_structured.cpac - Structured binary data
- pattern_random.cpac            - Pseudo-random data (low compression)

## Usage
All files should decompress successfully with cpac_engine::decompress().
Original data is deterministically generated, so roundtrip validation is possible.

## Regeneration
To regenerate all golden vectors:
```bash
cargo test -p cpac-engine --test generate_golden_vectors -- --ignored --nocapture
```
"#;
    
    let path = Path::new(GOLDEN_DIR).join("README.md");
    fs::write(&path, metadata).unwrap();
    println!("✓ Generated: {}", path.display());
}

/// Generate all golden vectors at once.
#[test]
#[ignore]
fn generate_all_golden_vectors() {
    println!("\n🔨 Generating all golden vectors...\n");
    generate_backend_golden_vectors();
    generate_edge_case_golden_vectors();
    generate_pattern_golden_vectors();
    generate_golden_metadata();
    println!("\n✅ All golden vectors generated!\n");
}
